spring:
  application:
    name: sims-user-service
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    whitelabel.enabled: false
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
